#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
valhost=`echo $(hostname) | cut -d'-' -f2- | rev | cut -d'-' -f2- | rev`
sudo sed -i '/^\http {/a\\tadd_header X-Served-By '"$valhost"';'\
 /etc/nginx/nginx.conf
sudo service nginx restart
