#!/usr/bin/env bash
# configures a brand new Ubuntu machine to the requirements asked in this task
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-1.8
sudo apt-get update
sudo apt-get install haproxy=1.8.\*
echo "frontend localnodes
	bind *:80
	default_backend nodes
backend nodes
	balance roundrobin
	server 384-web-01 35.231.97.140:80 check
	server 384-web-02 35.237.159.72:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg
echo "ENABLED=1" | sudo tee -a /etc/default/haproxy
sudo service haproxy restart
