#!/usr/bin/env bash
# transfers a file from our client to a server
ssh ubuntu@35.231.97.140 -i ~/.ssh/holberton 'apt-get update; sudo apt-get -y install nginx; echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html'
