#!/usr/bin/env bash
# transfers a file from our client to a server
sudo sed -i "/^\tserver_name localhost;/a location \/redirect_me \{\n\t\treturn 301 https://www.youtube.com/watch?v=$GUlwu4;\n\t\}" /etc/nginx/sites-available/default
sudo service nginx reload
